---
apiVersion: v1
kind: Namespace
metadata:
  name: ocp-etcd-backup
  labels:
    app: openshift-etcd-backup

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openshift-etcd-backup
  namespace: ocp-etcd-backup
  labels:
    app: openshift-etcd-backup

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-etcd-backup
rules:
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - get
      - list
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
      - create
      - delete
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-etcd-backup
  labels:
    app: openshift-etcd-backup
subjects:
  - kind: ServiceAccount
    name: openshift-etcd-backup
    namespace: ocp-etcd-backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-etcd-backup

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: openshift-backup
  namespace: ocp-etcd-backup
  labels:
    app: openshift-etcd-backup
spec:
  schedule: "00 00 * * 5" # Chaque Vendredi à Minuit.
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    metadata:
      labels:
        app: openshift-etcd-backup
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: openshift-etcd-backup
        spec:
          containers:
            - name: etcd-backup
              image: "registry.redhat.io/openshift4/ose-cli"
              command:
                - "/bin/bash"
                - "-c"
                - oc get no -l node-role.kubernetes.io/master --no-headers -o name | grep -i master-0 | xargs -I {} -- oc debug {} -- bash -c 'chroot /host  sudo -E mkdir -p /home/core/backup-etcd-c1-2/ && chroot /host  sudo -E  mount -t nfs x.x.x.x:/nfsShare/nfs-c1-2/etcd_backups /home/core/backup-etcd-c1-2/ && chroot /host sudo -E /usr/local/bin/cluster-backup.sh /home/core/backup-etcd-c1-2/'
          restartPolicy: "Never"
          terminationGracePeriodSeconds: 30
          activeDeadlineSeconds: 500
          dnsPolicy: "ClusterFirst"
          serviceAccountName: "openshift-backup"
          serviceAccount: "openshift-backup"
      
---